# CRE PROJECT SETTINGS FILE
# Rezoning Oracle — Townhall / ETHGlobal NYC 2026

staging-settings:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-rpc.publicnode.com
    - chain-name: hedera-testnet
      url: https://testnet.hashio.io/api

production-settings:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-rpc.publicnode.com
    - chain-name: hedera-testnet
      url: https://testnet.hashio.io/api
